# generated by datamodel-codegen:
#   filename:  sleep.json
#   timestamp: 2021-10-30T15:02:49+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Summary(BaseModel):
    totalMinutesAsleep: int
    totalSleepRecords: int
    totalTimeInBed: int


class SleepResponse(BaseModel):
    sleep: List
    summary: Summary
